<div class="complete-content">
    <!--Mid Content Start-->
    <div class="about-intro-wrap pull-left">

        <div class="bread-crumb-wrap ibc-wrap-6">
            <div class="container">
                <!--Title / Beadcrumb-->
                <div class="inner-page-title-wrap col-xs-12 col-md-12 col-sm-12">
                    <div class="bread-heading"><h1>Medical Treatment</h1></div>
                    <div class="bread-crumb pull-right">
                        <ul>
                            <li><a href="index-2.html">Home</a></li>
                            <li><a href="about-us-1.html">Departments</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="row">

                <div class="col-md-12 col-sm-12 col-lg-12 col-xs-12 dept-tabs-wrap wow fadeInUp animated" data-wow-delay="1s" data-wow-offset="200">

                    <!-- tabs left -->
                    <div class="tabbable tabs-left">
                        <ul class="nav nav-tabs col-md-4 col-sm-4 col-xs-5">
                            <li class="active"><a href="#a" data-toggle="tab"><i class="icon-eye-open dept-tabs-icon"></i><span class="tabs-heads">Laser Therapy</span><i class="right-arr"></i></a></li>
                            </ul>

                        <div class="tab-content col-md-8 col-sm-8 col-xs-7 pull-right">

                            <div class="fade tab-pane active in" id="a">
                                <div class="dept-title-tabs">Laser Therapy</div>
                                <img alt="" class="img-responsive" src="images/dept-dymmy.jpg" />
                                <div class="dept-subtitle-tabs">Laser Therapy</div>
                                <p>The laser light generated by low-powered (cold) lasers (low level Laser Therapy – LLLT) provides light energy to the hair roots which stimulate hair growth or regrowth.
								</p>
								<p>
								Laser Therapy Results – Before and After
								</P>
								<img src="">
                            </div>


                       
                        </div>



                        <div class="sidebar-wrap-dept col-md-4 col-sm-4 col-xs-12 no-pad wow fadeInUp animated" data-wow-delay="1s" data-wow-offset="200">

                            <div class="appointment-form no-pad dept-form">
                                <!--                            <div class="alert alert-success" id="appointmentSuccess" style="margin: 0 0 10px 0px;">
                                                                <strong>Success!</strong> Your message has been sent to us.
                                                            </div>
                                                            <div class="alert alert-danger" id="appointmentError" style="margin: 0 0 10px 0px;">
                                                                <strong>Error!</strong> There was an error sending your message.
                                                            </div>-->
                                <div class="appointment-form-title"><i class="icon-hospital2 appointment-form-icon"></i>Book An Appointment</div>
                                <form class="appt-form app-form" method="post">
                                    <select class="appt-form-select" name="department">
                                        <option>Select Department</option>
                                        <option>Select Department</option>
                                        <option>Select Department</option>
                                        <option>Select Department</option>
                                    </select>
                                    <input type="text" class="appt-form-txt" name="apt-first-name" id="apt-first-name" placeholder="First Name(required)">
                                    <label for="apt-first-name" class="apt-first-name-error error">This field is required.</label>

                                    <input type="text" class="appt-form-txt" name="apt-last-name" placeholder="Last Name">
                                    <input type="text" class="appt-form-txt" name="apt-phno" id="apt-phno" placeholder="Phone(required)">
                                    <label for="apt-phno" class="apt-phno-error error" style="display:block;">This field is required.</label>

                                    <input type="email" class="appt-form-txt" name="apt-email" id="apt-email" placeholder="Email(required)">
                                    <label for="apt-email" class="apt-email-error error">This field is required.</label>

                                    <input type="date" class="appt-form-txt" name="apt-date">
                                    <section class="color-7" id="btn-click">
                                        <button class="icon-mail btn2-st2 btn-7 btn-7b iform-button">Submit</button>
                                    </section>
                                </form>
                            </div>

                            <div class="dept-call-info wow fadeInUp animated idept-call" data-wow-delay="1s" data-wow-offset="200">
                                <div class="dept-phone"><div class="dep-ico1-wrap"><i class="icon-phone2 dept-phone-icon"></i></div><span class="ifont-normal">By Phone:</span> 1-800-345-6678</div>
                                <div class="dept-phone"><div class="dep-ico2-wrap"><i class="icon-mail dept-mail-icon"></i></div><span class="ifont-normal">By E-Mail:</span> <a href="mailto:contact@imedica.com">contact@imedica.com</a></div>
                            </div>
                        </div>
                        <!-- /tabs -->

                    </div>



                </div><!-- /row -->
            </div> 



        </div>
    </div>


</section>
</div>
<!--Mid Content End-->