<?php
//namespace Laravel\Lumen\Console\Commands;

namespace App\Console\Commands;


use Illuminate\Console\Command;

//use Illuminate\Console\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

class DeployRunnerCommand extends Command {


    /**
     * The console command name.
     *
     * @var string
     */
    protected $name = 'deploy:run';

    protected $signature = 'deploy:run {id?}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = "Deploy a project";

    public function run(InputInterface $input, OutputInterface $output): int {
        return parent::run($input, $output); // TODO: Change the autogenerated stub
    }


    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle() {
        chdir(base_path('storage'));
        $projectId = $this->argument('id');
        echo 'fire';
    }

}
